// ============================================================================
// CashFromChaos — core domain types
// ----------------------------------------------------------------------------
// These model the full autonomous recommerce operation: an item the seller no
// longer wants, the operator's analysis, the chosen marketplace, the listing,
// buyer negotiation under policy, payment custody, fulfillment and payout.
// ============================================================================

export type ItemCondition =
  | "new"
  | "like-new"
  | "good"
  | "fair"
  | "for-parts"
  | "unknown";

export type FulfillmentMode = "shipping" | "local-pickup" | "either";

export type Confidence = "low" | "medium" | "medium-high" | "high";

// ---------------------------------------------------------------------------
// Intake — the minimal human clue + photos
// ---------------------------------------------------------------------------
export interface ItemIntake {
  /** The seller's one-line clue, e.g. "I want to sell this guitar pedal". */
  clue: string;
  /** Photo URLs or data URIs. For the demo these are fixture images. */
  photos: string[];
  /** Optional free-text extra context from the seller. */
  notes?: string;
  /** Optional answers the seller gave to critical questions. */
  answers?: Record<string, string>;
}

// ---------------------------------------------------------------------------
// Analysis — what the operator understood about the item
// ---------------------------------------------------------------------------
export interface CriticalQuestion {
  id: string;
  /** Why the operator must ask this — affects price or policy materially. */
  reason: string;
  question: string;
  /** Suggested quick-reply chips for the seller UI. */
  options?: string[];
}

export interface ItemAnalysis {
  title: string;
  category: string;
  detectedAttributes: Record<string, string>;
  condition: ItemCondition;
  confidence: Confidence;
  /** Short, legible reasoning shown in the ops trace (NOT raw chain-of-thought). */
  rationale: string[];
  /** Only the questions that genuinely block a good decision. */
  missingInfo: CriticalQuestion[];
  /** Flags such as authenticity-sensitive, bulky, restricted, fragile. */
  flags: string[];
  estimatedMarketLow: number;
  estimatedMarketHigh: number;
  /**
   * Optional item-specific marketplace blurb generated by the live operator
   * (HermesBrain) from the seller's actual clue/photo. Absent on the
   * deterministic fixture path; when present it flows into the listing body.
   */
  description?: string;
  /** Optional short selling points generated alongside the description. */
  sellingPoints?: string[];
}

// ---------------------------------------------------------------------------
// Marketplace routing
// ---------------------------------------------------------------------------
export interface MarketplaceOption {
  channelId: string;
  name: string;
  fitScore: number; // 0..1
  reason: string;
  feePct: number;
  shippingFriendly: boolean;
}

export interface MarketplacePlan {
  primary: MarketplaceOption;
  alternates: MarketplaceOption[];
  bundleRecommended: boolean;
  strategy: string[];
}

// ---------------------------------------------------------------------------
// Listing drafts (per channel)
// ---------------------------------------------------------------------------
export interface ListingDraft {
  channelId: string;
  title: string;
  body: string;
  tags: string[];
  price: number;
  currency: "USD";
}

// ---------------------------------------------------------------------------
// Policy — the visible safety / autonomy layer
// ---------------------------------------------------------------------------
export interface CommercePolicy {
  currency: "USD";
  targetPrice: number;
  floorPrice: number;
  autoAcceptAtOrAbove: number;
  autoCounterDownTo: number;
  requireHumanBelow: number;
  maxFulfillmentSpend: number;
  allowedPaymentMethods: string[];
  allowedChannels: string[];
  shippingAllowed: boolean;
  pickupAllowed: boolean;
  suspiciousBuyerEscalation: boolean;
}

// ---------------------------------------------------------------------------
// Negotiation
// ---------------------------------------------------------------------------
export type NegotiationDecision =
  | "accept"
  | "counter"
  | "reject"
  | "escalate-human"
  | "answer"; // informational reply, no price movement

export interface BuyerMessage {
  itemId: string;
  buyerName: string;
  text: string;
  offer?: number; // numeric offer if the buyer named a price
  ts: number;
}

export interface AgentReply {
  decision: NegotiationDecision;
  /** Price the agent proposes/accepts, if applicable. */
  price?: number;
  reply: string;
  /** Concise reason shown in the ops trace. */
  reason: string;
  /** True if a deal is now agreed and the buyer can pay. */
  dealAgreed: boolean;
  agreedPrice?: number;
}

// ---------------------------------------------------------------------------
// Transaction / fulfillment / payout
// ---------------------------------------------------------------------------
export type TransactionStatus =
  | "analyzed"
  | "listed"
  | "buyer-engaged"
  | "offer-accepted"
  | "paid"
  | "shipping-required"
  | "in-transit"
  | "delivered"
  | "payout-released"
  | "escalated";

export interface FulfillmentPlan {
  mode: FulfillmentMode;
  carrier?: string;
  labelCost: number;
  instruction: string;
  windowHours: number;
}

export interface LedgerEntry {
  label: string;
  amount: number; // positive = inflow to seller, negative = cost
  kind: "revenue" | "fee" | "shipping" | "boost" | "payout";
}

export interface Payment {
  provider: "stripe" | "simulated";
  status: "none" | "pending" | "held" | "released" | "failed";
  amount: number;
  checkoutUrl?: string;
  sessionId?: string;
}

// ---------------------------------------------------------------------------
// The aggregate record the dashboard renders
// ---------------------------------------------------------------------------
export interface Item {
  id: string;
  createdAt: number;
  intake: ItemIntake;
  analysis: ItemAnalysis;
  plan: MarketplacePlan;
  policy: CommercePolicy;
  listings: ListingDraft[];
  status: TransactionStatus;
  messages: BuyerMessage[];
  agentReplies: AgentReply[];
  payment: Payment;
  fulfillment?: FulfillmentPlan;
  ledger: LedgerEntry[];
  /** Append-only operational trace for the dashboard. */
  trace: TraceEvent[];
}

export interface TraceEvent {
  ts: number;
  actor: "operator" | "buyer" | "seller" | "system" | "stripe";
  label: string;
  detail?: string;
  level?: "info" | "decision" | "money" | "warn";
}

// ---------------------------------------------------------------------------
// The operator interface — swappable brains (fixture / LLM / Hermes)
// ---------------------------------------------------------------------------
export interface OperatorBrain {
  readonly name: string;
  analyzeItem(input: ItemIntake): Promise<ItemAnalysis>;
  chooseMarketplace(input: ItemAnalysis): Promise<MarketplacePlan>;
  buildPolicy(analysis: ItemAnalysis, plan: MarketplacePlan): Promise<CommercePolicy>;
  draftListings(
    analysis: ItemAnalysis,
    plan: MarketplacePlan,
    policy: CommercePolicy
  ): Promise<ListingDraft[]>;
  handleBuyerMessage(
    item: Item,
    message: BuyerMessage
  ): Promise<AgentReply>;
  decideFulfillment(item: Item): Promise<FulfillmentPlan>;
}
